apiVersion: apps/v1
kind: Deployment
metadata:
  name: bucket-operator
spec:
  replicas: 1
  selector:
    matchLabels:
      name: bucket-operator
  template:
    metadata:
      labels:
        name: bucket-operator
    spec:
      serviceAccountName: bucket-operator
      containers:
        - name: bucket-operator
          # Replace this with the built image name
          image: leg100/bucket-operator:latest
          command:
          - bucket-operator
          imagePullPolicy: Always
          env:
            - name: WATCH_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: OPERATOR_NAME
              value: "bucket-operator"
            - name: GOOGLE_APPLICATION_CREDENTIALS
              value: /credentials/key.json
          volumeMounts:
            - name: credentials
              mountPath: /credentials
      volumes:
        - name: credentials
          secret:
            secretName: bucket-operator
